# 数据库

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/custom_resource_manager?serverTimezone=Asia/Shanghai&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    #指定数据源
    type: com.alibaba.druid.pool.DruidDataSource



#    type: com.alibaba.druid.pool.DruidDataSource

    druid:
      url: jdbc:mysql://localhost:3306/custom_resource_manager?serverTimezone=UTC
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver

# mybatis-plus
mybatis-plus:
  type-aliases-package: com.crm.dao.entity
  #  配置指定mapper文件路径
  mapper-locations: classpath:mapper/*.xml


